// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Offer struct {
	ID        string
	Title     string
	Company   string
	Location  string
	PostedAt  time.Time
	CreatedAt time.Time
}

type Query struct {
	ID        int64
	Keywords  string
	Location  string
	CreatedAt time.Time
	QueriedAt time.Time
}

type QueryOffer struct {
	QueryID int64
	OfferID string
}
