// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Offer struct {
	ID        string
	QueryID   int64
	Title     string
	Company   string
	Location  string
	Ignored   bool
	PostedAt  time.Time
	CreatedAt sql.NullTime
}

type Query struct {
	ID        int64
	Keywords  string
	Location  string
	FTpr      string
	FJt       string
	CreatedAt sql.NullTime
}
