// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOffer = `-- name: CreateOffer :exec
INSERT INTO offers (id, title, company, location, posted_at, description, source, url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO NOTHING
`

type CreateOfferParams struct {
	ID          string
	Title       string
	Company     string
	Location    string
	PostedAt    pgtype.Timestamptz
	Description string
	Source      string
	Url         string
}

func (q *Queries) CreateOffer(ctx context.Context, arg *CreateOfferParams) error {
	_, err := q.db.Exec(ctx, createOffer,
		arg.ID,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.PostedAt,
		arg.Description,
		arg.Source,
		arg.Url,
	)
	return err
}

const createQuery = `-- name: CreateQuery :one
INSERT INTO
    queries (keywords, location)
VALUES
    ($1, $2) RETURNING id, keywords, location, created_at, queried_at, updated_at
`

type CreateQueryParams struct {
	Keywords string
	Location string
}

func (q *Queries) CreateQuery(ctx context.Context, arg *CreateQueryParams) (*Query, error) {
	row := q.db.QueryRow(ctx, createQuery, arg.Keywords, arg.Location)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.Location,
		&i.CreatedAt,
		&i.QueriedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createQueryOfferAssoc = `-- name: CreateQueryOfferAssoc :exec
INSERT INTO query_offers (query_id, offer_id)
VALUES ($1, $2)
ON CONFLICT (query_id, offer_id) DO NOTHING
`

type CreateQueryOfferAssocParams struct {
	QueryID int64
	OfferID string
}

func (q *Queries) CreateQueryOfferAssoc(ctx context.Context, arg *CreateQueryOfferAssocParams) error {
	_, err := q.db.Exec(ctx, createQueryOfferAssoc, arg.QueryID, arg.OfferID)
	return err
}

const deleteOldOffers = `-- name: DeleteOldOffers :exec
DELETE FROM offers
WHERE posted_at < NOW() - INTERVAL '7 days'
`

func (q *Queries) DeleteOldOffers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldOffers)
	return err
}

const deleteQuery = `-- name: DeleteQuery :exec
DELETE FROM queries
WHERE
    id = $1
`

func (q *Queries) DeleteQuery(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteQuery, id)
	return err
}

const getQuery = `-- name: GetQuery :one
SELECT
    id, keywords, location, created_at, queried_at, updated_at
FROM
    queries
WHERE
    keywords = $1
    AND location = $2
`

type GetQueryParams struct {
	Keywords string
	Location string
}

func (q *Queries) GetQuery(ctx context.Context, arg *GetQueryParams) (*Query, error) {
	row := q.db.QueryRow(ctx, getQuery, arg.Keywords, arg.Location)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.Location,
		&i.CreatedAt,
		&i.QueriedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getQueryByID = `-- name: GetQueryByID :one
SELECT
    id, keywords, location, created_at, queried_at, updated_at
FROM
    queries
WHERE
    id = $1
`

func (q *Queries) GetQueryByID(ctx context.Context, id int64) (*Query, error) {
	row := q.db.QueryRow(ctx, getQueryByID, id)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.Location,
		&i.CreatedAt,
		&i.QueriedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getQueryScraper = `-- name: GetQueryScraper :one
WITH q AS (
    SELECT id, keywords, location, created_at, queried_at, updated_at
    FROM queries
    WHERE id = $1
),
ins AS (
    INSERT INTO query_scraper_status (query_id, scraper_name)
    SELECT q.id, $2
    FROM q
    WHERE NOT EXISTS (
        SELECT 1
        FROM query_scraper_status s
        WHERE s.query_id = q.id
          AND s.scraper_name = $2
    )
    RETURNING query_id, scraper_name, scraped_at
),
s AS (
    SELECT query_id, scraper_name, scraped_at
    FROM query_scraper_status
    WHERE query_id = $1
      AND scraper_name = $2

    UNION ALL

    SELECT query_id, scraper_name, scraped_at
    FROM ins
)
SELECT
    q.id, q.keywords, q.location, q.created_at, q.queried_at, q.updated_at,
    s.scraped_at
FROM q
JOIN s ON s.query_id = q.id
`

type GetQueryScraperParams struct {
	ID          int64
	ScraperName string
}

type GetQueryScraperRow struct {
	ID        int64
	Keywords  string
	Location  string
	CreatedAt pgtype.Timestamptz
	QueriedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ScrapedAt pgtype.Timestamptz
}

func (q *Queries) GetQueryScraper(ctx context.Context, arg *GetQueryScraperParams) (*GetQueryScraperRow, error) {
	row := q.db.QueryRow(ctx, getQueryScraper, arg.ID, arg.ScraperName)
	var i GetQueryScraperRow
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.Location,
		&i.CreatedAt,
		&i.QueriedAt,
		&i.UpdatedAt,
		&i.ScrapedAt,
	)
	return &i, err
}

const listOffers = `-- name: ListOffers :many
SELECT
    o.id, o.title, o.company, o.location, o.posted_at, o.created_at, o.source, o.url, o.description
FROM
    queries q
    JOIN query_offers qo ON q.id = qo.query_id
    JOIN offers o ON qo.offer_id = o.id
WHERE
    q.id = $1
ORDER BY
    o.posted_at DESC
`

func (q *Queries) ListOffers(ctx context.Context, id int64) ([]*Offer, error) {
	rows, err := q.db.Query(ctx, listOffers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.PostedAt,
			&i.CreatedAt,
			&i.Source,
			&i.Url,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueries = `-- name: ListQueries :many
SELECT
    id, keywords, location, created_at, queried_at, updated_at
FROM
    queries
`

func (q *Queries) ListQueries(ctx context.Context) ([]*Query, error) {
	rows, err := q.db.Query(ctx, listQueries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Query
	for rows.Next() {
		var i Query
		if err := rows.Scan(
			&i.ID,
			&i.Keywords,
			&i.Location,
			&i.CreatedAt,
			&i.QueriedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQueryQAT = `-- name: UpdateQueryQAT :exec
UPDATE queries
SET
    queried_at = CURRENT_TIMESTAMP
WHERE
    id = $1
`

func (q *Queries) UpdateQueryQAT(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateQueryQAT, id)
	return err
}

const updateQueryScrapedAt = `-- name: UpdateQueryScrapedAt :exec
UPDATE query_scraper_status
SET scraped_at = CURRENT_TIMESTAMP
WHERE query_id = $1
  AND scraper_name = $2
`

type UpdateQueryScrapedAtParams struct {
	QueryID     int64
	ScraperName string
}

func (q *Queries) UpdateQueryScrapedAt(ctx context.Context, arg *UpdateQueryScrapedAtParams) error {
	_, err := q.db.Exec(ctx, updateQueryScrapedAt, arg.QueryID, arg.ScraperName)
	return err
}

const updateQueryUAT = `-- name: UpdateQueryUAT :exec
UPDATE queries
SET
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1
`

func (q *Queries) UpdateQueryUAT(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateQueryUAT, id)
	return err
}
