// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const createOffer = `-- name: CreateOffer :exec
INSERT
OR IGNORE INTO offers (id, title, company, location, posted_at)
VALUES
    (?, ?, ?, ?, ?)
`

type CreateOfferParams struct {
	ID       string
	Title    string
	Company  string
	Location string
	PostedAt time.Time
}

func (q *Queries) CreateOffer(ctx context.Context, arg *CreateOfferParams) error {
	_, err := q.db.ExecContext(ctx, createOffer,
		arg.ID,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.PostedAt,
	)
	return err
}

const createQuery = `-- name: CreateQuery :one
INSERT INTO
    queries (keywords, location)
VALUES
    (?, ?) RETURNING id, keywords, location, created_at, queried_at, updated_at
`

type CreateQueryParams struct {
	Keywords string
	Location string
}

func (q *Queries) CreateQuery(ctx context.Context, arg *CreateQueryParams) (*Query, error) {
	row := q.db.QueryRowContext(ctx, createQuery, arg.Keywords, arg.Location)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.Location,
		&i.CreatedAt,
		&i.QueriedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createQueryOfferAssoc = `-- name: CreateQueryOfferAssoc :exec
INSERT
OR IGNORE INTO query_offers (query_id, offer_id)
VALUES
    (?, ?)
`

type CreateQueryOfferAssocParams struct {
	QueryID int64
	OfferID string
}

func (q *Queries) CreateQueryOfferAssoc(ctx context.Context, arg *CreateQueryOfferAssocParams) error {
	_, err := q.db.ExecContext(ctx, createQueryOfferAssoc, arg.QueryID, arg.OfferID)
	return err
}

const deleteQuery = `-- name: DeleteQuery :exec
DELETE FROM queries
WHERE
    id = ?
`

func (q *Queries) DeleteQuery(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteQuery, id)
	return err
}

const getQuery = `-- name: GetQuery :one
SELECT
    id, keywords, location, created_at, queried_at, updated_at
FROM
    queries
WHERE
    keywords = ?
    AND location = ?
`

type GetQueryParams struct {
	Keywords string
	Location string
}

func (q *Queries) GetQuery(ctx context.Context, arg *GetQueryParams) (*Query, error) {
	row := q.db.QueryRowContext(ctx, getQuery, arg.Keywords, arg.Location)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.Location,
		&i.CreatedAt,
		&i.QueriedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getQueryByID = `-- name: GetQueryByID :one
SELECT
    id, keywords, location, created_at, queried_at, updated_at
FROM
    queries
WHERE
    id = ?
`

func (q *Queries) GetQueryByID(ctx context.Context, id int64) (*Query, error) {
	row := q.db.QueryRowContext(ctx, getQueryByID, id)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Keywords,
		&i.Location,
		&i.CreatedAt,
		&i.QueriedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listOffers = `-- name: ListOffers :many
SELECT
    o.id, o.title, o.company, o.location, o.posted_at, o.created_at
FROM
    queries q
    JOIN query_offers qo ON q.id = qo.query_id
    JOIN offers o ON qo.offer_id = o.id
WHERE
    q.id = ?
    AND o.posted_at >= ?
ORDER BY
    o.posted_at DESC
`

type ListOffersParams struct {
	ID       int64
	PostedAt time.Time
}

func (q *Queries) ListOffers(ctx context.Context, arg *ListOffersParams) ([]*Offer, error) {
	rows, err := q.db.QueryContext(ctx, listOffers, arg.ID, arg.PostedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.PostedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueries = `-- name: ListQueries :many
SELECT
    id
FROM
    queries
`

func (q *Queries) ListQueries(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listQueries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQueryQAT = `-- name: UpdateQueryQAT :exec
UPDATE queries
SET
    queried_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

func (q *Queries) UpdateQueryQAT(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateQueryQAT, id)
	return err
}

const updateQueryUAT = `-- name: UpdateQueryUAT :exec
UPDATE queries
SET
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

func (q *Queries) UpdateQueryUAT(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateQueryUAT, id)
	return err
}
